[2025-02-23T15:52:37.948+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:37.979+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-23T15:52:38.015+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-23T15:52:38.017+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:38.043+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-02-01 00:00:00+00:00
[2025-02-23T15:52:38.063+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1419) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:38.063+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'third_task', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpxvp0p4az']
[2025-02-23T15:52:38.069+0000] {standard_task_runner.py:72} INFO - Started process 1435 to run task
[2025-02-23T15:52:38.070+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask third_task
[2025-02-23T15:52:38.148+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.third_task scheduled__2025-02-01T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:38.254+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-02-23T15:52:38.257+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:38.280+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:38.282+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo finally, it will be done!!!']
[2025-02-23T15:52:38.293+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:38.296+0000] {subprocess.py:106} INFO - finally, it will be done!!!
[2025-02-23T15:52:38.296+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:38.344+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:38.353+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=third_task, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250223T155237, end_date=20250223T155238
[2025-02-23T15:52:38.581+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:38.607+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:38.614+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:13.345+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:13.382+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-24T04:47:13.396+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-24T04:47:13.397+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:13.517+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-02-01 00:00:00+00:00
[2025-02-24T04:47:13.533+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=824) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:13.535+0000] {standard_task_runner.py:72} INFO - Started process 840 to run task
[2025-02-24T04:47:13.540+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'third_task', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpuzihd_1w']
[2025-02-24T04:47:13.550+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask third_task
[2025-02-24T04:47:13.646+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.third_task scheduled__2025-02-01T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:13.744+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-02-24T04:47:13.747+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:13.773+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:13.776+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo finally, it will be done!!!']
[2025-02-24T04:47:13.802+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:13.803+0000] {subprocess.py:106} INFO - finally, it will be done!!!
[2025-02-24T04:47:13.804+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:13.866+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:13.867+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=third_task, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250224T044713, end_date=20250224T044713
[2025-02-24T04:47:14.044+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:14.089+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:14.092+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
