[2025-02-24T05:05:21.454+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T05:05:21.499+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_1.third_task scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-24T05:05:21.527+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_1.third_task scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-24T05:05:21.528+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T05:05:21.559+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-02-11 00:00:00+00:00
[2025-02-24T05:05:21.569+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2019) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T05:05:21.575+0000] {standard_task_runner.py:72} INFO - Started process 2037 to run task
[2025-02-24T05:05:21.579+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_1', 'third_task', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmp0x4jxeiw']
[2025-02-24T05:05:21.583+0000] {standard_task_runner.py:105} INFO - Job 171: Subtask third_task
[2025-02-24T05:05:21.696+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_1.third_task scheduled__2025-02-11T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T05:05:21.803+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag_1' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-24T05:05:21.804+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T05:05:21.824+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T05:05:21.826+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo finally, it will be done!!!']
[2025-02-24T05:05:21.837+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T05:05:21.838+0000] {subprocess.py:106} INFO - finally, it will be done!!!
[2025-02-24T05:05:21.839+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T05:05:21.872+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T05:05:21.873+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag_1, task_id=third_task, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250224T050521, end_date=20250224T050521
[2025-02-24T05:05:21.965+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T05:05:21.986+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
