[2025-02-23T15:52:36.827+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:36.861+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-23T15:52:36.875+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-23T15:52:36.876+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:36.962+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-02 00:00:00+00:00
[2025-02-23T15:52:36.974+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1366) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:36.976+0000] {standard_task_runner.py:72} INFO - Started process 1380 to run task
[2025-02-23T15:52:36.976+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-02T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmp259qcfu4']
[2025-02-23T15:52:36.983+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask second_task
[2025-02-23T15:52:37.075+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-02T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:37.193+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T00:00:00+00:00'
[2025-02-23T15:52:37.194+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:37.231+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:37.232+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-23T15:52:37.246+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:37.249+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-23T15:52:37.252+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:37.305+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:37.307+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-02T00:00:00+00:00, execution_date=20250202T000000, start_date=20250223T155236, end_date=20250223T155237
[2025-02-23T15:52:37.473+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:37.509+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:37.512+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:13.330+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:13.373+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-24T04:47:13.395+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-24T04:47:13.395+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:13.508+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-02 00:00:00+00:00
[2025-02-24T04:47:13.524+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=821) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:13.525+0000] {standard_task_runner.py:72} INFO - Started process 838 to run task
[2025-02-24T04:47:13.519+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-02T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpn4w54n76']
[2025-02-24T04:47:13.530+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask second_task
[2025-02-24T04:47:13.659+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-02T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:13.750+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T00:00:00+00:00'
[2025-02-24T04:47:13.751+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:13.771+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:13.772+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-24T04:47:13.795+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:13.798+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-24T04:47:13.804+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:13.858+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:13.864+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-02T00:00:00+00:00, execution_date=20250202T000000, start_date=20250224T044713, end_date=20250224T044713
[2025-02-24T04:47:14.069+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:14.116+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:14.124+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
