[2025-02-23T15:52:44.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:44.449+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-23T15:52:44.461+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-23T15:52:44.462+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:44.483+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-19 00:00:00+00:00
[2025-02-23T15:52:44.493+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1564) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:44.494+0000] {standard_task_runner.py:72} INFO - Started process 1583 to run task
[2025-02-23T15:52:44.493+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpvsr4mzcp']
[2025-02-23T15:52:44.495+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask second_task
[2025-02-23T15:52:44.547+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-19T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:44.643+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-23T15:52:44.644+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:44.664+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:44.665+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-23T15:52:44.674+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:44.675+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-23T15:52:44.676+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:44.702+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:44.703+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-19T00:00:00+00:00, execution_date=20250219T000000, start_date=20250223T155244, end_date=20250223T155244
[2025-02-23T15:52:44.750+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:44.773+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:44.775+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:22.539+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:22.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-24T04:47:22.594+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-24T04:47:22.594+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:22.621+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-19 00:00:00+00:00
[2025-02-24T04:47:22.631+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1121) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:22.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpifsq30in']
[2025-02-24T04:47:22.634+0000] {standard_task_runner.py:72} INFO - Started process 1136 to run task
[2025-02-24T04:47:22.634+0000] {standard_task_runner.py:105} INFO - Job 96: Subtask second_task
[2025-02-24T04:47:22.729+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-19T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:22.883+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-24T04:47:22.884+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:22.905+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:22.910+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-24T04:47:22.923+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:22.924+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-24T04:47:22.926+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:22.965+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:22.967+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-19T00:00:00+00:00, execution_date=20250219T000000, start_date=20250224T044722, end_date=20250224T044722
[2025-02-24T04:47:23.014+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:23.051+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:23.054+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
