[2025-02-23T15:52:37.715+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:37.752+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-23T15:52:37.768+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-23T15:52:37.769+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:37.934+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-08 00:00:00+00:00
[2025-02-23T15:52:37.946+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpl3udstew']
[2025-02-23T15:52:37.949+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask second_task
[2025-02-23T15:52:37.951+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1407) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:37.952+0000] {standard_task_runner.py:72} INFO - Started process 1425 to run task
[2025-02-23T15:52:38.046+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-08T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:38.195+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-23T15:52:38.196+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:38.221+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:38.222+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-23T15:52:38.237+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:38.238+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-23T15:52:38.239+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:38.274+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:38.275+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-08T00:00:00+00:00, execution_date=20250208T000000, start_date=20250223T155237, end_date=20250223T155238
[2025-02-23T15:52:38.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:38.412+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:38.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:14.647+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:14.679+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-24T04:47:14.702+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-24T04:47:14.702+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:14.723+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-08 00:00:00+00:00
[2025-02-24T04:47:14.737+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=891) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:14.745+0000] {standard_task_runner.py:72} INFO - Started process 909 to run task
[2025-02-24T04:47:14.742+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpeib0iiql']
[2025-02-24T04:47:14.754+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask second_task
[2025-02-24T04:47:14.872+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-08T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:15.007+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-24T04:47:15.010+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:15.029+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:15.030+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-24T04:47:15.041+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:15.044+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-24T04:47:15.045+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:15.098+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:15.099+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-08T00:00:00+00:00, execution_date=20250208T000000, start_date=20250224T044714, end_date=20250224T044715
[2025-02-24T04:47:15.187+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:15.241+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:15.249+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
