[2025-02-23T15:52:39.068+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:39.097+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-23T15:52:39.111+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-23T15:52:39.113+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:39.201+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-14 00:00:00+00:00
[2025-02-23T15:52:39.220+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1479) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:39.222+0000] {standard_task_runner.py:72} INFO - Started process 1492 to run task
[2025-02-23T15:52:39.220+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-14T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpgb3cw6yf']
[2025-02-23T15:52:39.223+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask second_task
[2025-02-23T15:52:39.292+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-14T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:39.392+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T00:00:00+00:00'
[2025-02-23T15:52:39.395+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:39.415+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:39.416+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-23T15:52:39.426+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:39.428+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-23T15:52:39.429+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:39.459+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:39.460+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-14T00:00:00+00:00, execution_date=20250214T000000, start_date=20250223T155239, end_date=20250223T155239
[2025-02-23T15:52:39.518+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:39.544+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:39.546+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:16.297+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:16.331+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-24T04:47:16.353+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-24T04:47:16.356+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:16.385+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-14 00:00:00+00:00
[2025-02-24T04:47:16.398+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=975) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:16.398+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-02-14T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpnsg59r0z']
[2025-02-24T04:47:16.404+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask second_task
[2025-02-24T04:47:16.403+0000] {standard_task_runner.py:72} INFO - Started process 1003 to run task
[2025-02-24T04:47:16.483+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-02-14T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:16.598+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T00:00:00+00:00'
[2025-02-24T04:47:16.599+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:16.618+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:16.624+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-24T04:47:16.635+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:16.638+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-24T04:47:16.639+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:16.712+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:16.714+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-02-14T00:00:00+00:00, execution_date=20250214T000000, start_date=20250224T044716, end_date=20250224T044716
[2025-02-24T04:47:16.950+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:16.988+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:16.998+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
