[2025-02-23T15:52:42.906+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:42.926+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-23T15:52:42.941+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-23T15:52:42.942+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:42.964+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-19 00:00:00+00:00
[2025-02-23T15:52:42.971+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1540) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:42.973+0000] {standard_task_runner.py:72} INFO - Started process 1547 to run task
[2025-02-23T15:52:42.972+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'first_task', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpo9_itu5x']
[2025-02-23T15:52:42.975+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask first_task
[2025-02-23T15:52:43.026+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.first_task scheduled__2025-02-19T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:43.150+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-23T15:52:43.152+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:43.172+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:43.173+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world! the first task is defined!!!']
[2025-02-23T15:52:43.184+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:43.186+0000] {subprocess.py:106} INFO - hello world! the first task is defined!!!
[2025-02-23T15:52:43.188+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:43.215+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:43.216+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=first_task, run_id=scheduled__2025-02-19T00:00:00+00:00, execution_date=20250219T000000, start_date=20250223T155242, end_date=20250223T155243
[2025-02-23T15:52:43.271+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:43.303+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:43.305+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:21.761+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:21.780+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-24T04:47:21.793+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-24T04:47:21.794+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:21.813+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-19 00:00:00+00:00
[2025-02-24T04:47:21.819+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1093) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:21.819+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'first_task', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmp2nktctdv']
[2025-02-24T04:47:21.820+0000] {standard_task_runner.py:72} INFO - Started process 1102 to run task
[2025-02-24T04:47:21.821+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask first_task
[2025-02-24T04:47:21.874+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.first_task scheduled__2025-02-19T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:21.980+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-24T04:47:21.981+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:22.001+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:22.002+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world! the first task is defined!!!']
[2025-02-24T04:47:22.013+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:22.015+0000] {subprocess.py:106} INFO - hello world! the first task is defined!!!
[2025-02-24T04:47:22.019+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:22.050+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:22.051+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=first_task, run_id=scheduled__2025-02-19T00:00:00+00:00, execution_date=20250219T000000, start_date=20250224T044721, end_date=20250224T044722
[2025-02-24T04:47:22.156+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:22.195+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:22.197+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
