[2025-02-23T15:52:39.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:39.592+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-23T15:52:39.603+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-23T15:52:39.604+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:39.620+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-02-13 00:00:00+00:00
[2025-02-23T15:52:39.627+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1503) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:39.628+0000] {standard_task_runner.py:72} INFO - Started process 1510 to run task
[2025-02-23T15:52:39.627+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'third_task', 'scheduled__2025-02-13T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmp08nk1s97']
[2025-02-23T15:52:39.629+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask third_task
[2025-02-23T15:52:39.674+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.third_task scheduled__2025-02-13T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:39.758+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-13T00:00:00+00:00'
[2025-02-23T15:52:39.759+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:39.771+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:39.772+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo finally, it will be done!!!']
[2025-02-23T15:52:39.780+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:39.781+0000] {subprocess.py:106} INFO - finally, it will be done!!!
[2025-02-23T15:52:39.782+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:39.803+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:39.804+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=third_task, run_id=scheduled__2025-02-13T00:00:00+00:00, execution_date=20250213T000000, start_date=20250223T155239, end_date=20250223T155239
[2025-02-23T15:52:39.844+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:39.858+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:39.860+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:16.024+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:16.077+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-24T04:47:16.096+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-24T04:47:16.096+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:16.118+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-02-13 00:00:00+00:00
[2025-02-24T04:47:16.130+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=967) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:16.134+0000] {standard_task_runner.py:72} INFO - Started process 988 to run task
[2025-02-24T04:47:16.137+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'third_task', 'scheduled__2025-02-13T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpe3u18d_a']
[2025-02-24T04:47:16.146+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask third_task
[2025-02-24T04:47:16.228+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.third_task scheduled__2025-02-13T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:16.344+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-13T00:00:00+00:00'
[2025-02-24T04:47:16.345+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:16.365+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:16.366+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo finally, it will be done!!!']
[2025-02-24T04:47:16.386+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:16.387+0000] {subprocess.py:106} INFO - finally, it will be done!!!
[2025-02-24T04:47:16.389+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:16.432+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:16.433+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=third_task, run_id=scheduled__2025-02-13T00:00:00+00:00, execution_date=20250213T000000, start_date=20250224T044716, end_date=20250224T044716
[2025-02-24T04:47:16.647+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:16.705+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:16.713+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
